version: '3.8'

services:
  frontend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - celebration-network
    restart: unless-stopped
    environment:
      - API_URL=http://api:8000/api

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - celebration-network
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - DEBUG=false

networks:
  celebration-network:
    driver: bridge
